[package]
name = "cure-kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader_api = "0.11.12"
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
x86_64 = { version = "0.15.2", features = ["instructions"] }
corosensei = { version = "0.3.1", default-features = false }
spin = "0.10.0"
raw-cpuid = "11.6.0"
acpi = "6.0.1"
linked_list_allocator = "0.10.5"
once_cell = { version = "1.19", default-features = false, features = ["alloc"] }

[dependencies.crossbeam-queue]
version = "0.3.12"
default-features = false
features = ["alloc"]

[dependencies.conquer-once]
version = "0.4.0"
default-features = false

[dependencies.futures-util]
version = "0.3.31"
default-features = false
features = ["alloc"]

#[package.metadata.bootloader]
#map-physical-memory = true
#physical-memory-offset = "0xFFFF800000000000"