// Ref: Intel Manuel Vol. 3 Figure 6-1
#define FAULT_DIVISION_ERROR            0x0
#define FAULT_TRAP_GEBUG_EXCEPTION      0x1
#define INT_NMI                         0x2
#define TRAP_BREAKPOINT                 0x3
#define TRAP_OVREFLOW                   0x4
#define FAULT_BOUND_EXCEED              0x5
#define FAULT_INVALID_OPCOED            0x6
#define FAULT_NO_MATH_PROCESSOR         0x7
#define ABORT_DOUBLE_FAULT              0x8
#define FAULT_RESERVED_0                0x9
#define FAULT_INVALID_TSS               0xA
#define FAULT_SEG_NOT_PRESENT           0xB
#define FAULT_STACK_SEG_FAULT           0xC
#define FAULT_GENERAL_PROTECTION        0xD
#define FAULT_PAGE_FAULT                0xE
#define FAULT_RESERVED_1                0xF
#define FAULT_x87_FAULT                 0x10
#define FAULT_ALIGNMENT_CHECK           0x11
#define FAULT_MACHINE_CHECK             0x12
#define FAULT_SIMD_FP_EXCEPTION         0x13
#define FAULT_VIRTUALIZATION_EXCEPTION  0x14
#define FAULT_CONTROL_PROTECTION        0x15